### ISSUE TITLE
Cannot type using android virtual keyboard

### ISSUE THREAD

**Issue by steve13814** [novnc/noVNC#856] opened 2017-07-07 08:27 UTC
Found that I cannot type anything in noVNC using Chrome on Nexus 6P or iPad, but Chrome on PC is fine.
Also found that I can reproduce this issue in Android Emulator (emulating Nexus 5X), so I record a video to show how to reproduce this issue.
https://www.youtube.com/watch?v=2Z06dwfvZ2k
However, there's still some difference between Nexus 6P and Android Emulator.

Device | Can input via virtual keyboard | Cannot input via virtual keyboard
--- | --- | ---
In Android Emulator using master branch noVNC | digits, enter, backspace | alphabets, symbol  |
In Nexus 6P using master branch noVNC  | enter, backspace| alphabets, symbol, digits |
In Android Emulator using v0.6.2 noVNC | alphabets, symbol (but some symbols are not work as expected), digits, enter, backspace  |   |
In Nexus 6P using v0.6.2 noVNC  | alphabets, symbol (but some symbols are not work as expected), digits, enter, backspace  |   |

#### Server side:
Ubuntu 16.04
nginx 1.10.3
npm version 3.10.10
node v6.11.0
noVNC master branch (latest 2017-07-06 commit 8f8c1803ffb25f6ed491279fa6f3fb4f4934e710)

#### Client side:
PC: Chrome 58.0.3029.33 (64-bit)
Android Emulator: Chrome 58.0.3029.121

### Here's the step:
git clone https://github.com/novnc/noVNC.git
npm install
node ./utils/use_require.js --as commonjs --with-app
Open browser to http://x.x.x.x/noVNC/build/vnc.html?host=y.y.y.y&port=z&autoconnect=true
git checkout -b v0.6.2 v0.6.2
Open browser to http://x.x.x.x/noVNC/vnc.html?host=y.y.y.y&port=z&autoconnect=true

**Comment by CendioOssman** [comment] 2017-07-07 09:54
I'm afraid I'm unable to reproduce this. I tried Chrome on iOS and on a Pixel C. In both cases enter and backspace worked just fine. What VNC server are you using?

**Comment by steve13814** [comment] 2017-07-07 09:57
websocket created by qemu 2.7.1

Oops, I found the table content is wrong. Let me fix it.

**Comment by CendioOssman** [comment] 2017-07-07 10:12
Ah. Then it might be a QEMU bug. The latest noVNC supports the QEMU Extended Keyboard Events. Perhaps QEMU gets confused when some keys include the physical key and some do not?

@berrange, any insight? gtk-vnc seems to send 0 for the physical key when it fails to map it, so it should be the de facto way to handle things.

**Comment by CendioOssman** [comment] 2017-07-07 10:17
Yup, it seems like QEMU cannot deal with this case:

https://github.com/berrange/qemu/blob/master/ui/vnc.c#L1962

It should have been `if (keyboard_layout || !keycode)` there.

**Comment by berrange** [comment] 2017-07-07 10:21
it isn't a QEMU bug, its a client bug. When the extended keyboard event has been activated clients must *always* send non-0 scancodes. If GTK-VNC is sending 0, that's a GTK-VNC bug to fix.

**Comment by CendioOssman** [comment] 2017-07-07 10:26
So what to do when the scan code isn't known? Mix standard VNC key events and QEMU extended key events?

**Comment by berrange** [comment] 2017-07-07 10:31
Just sending the keysym won't be much use - the remote QEMU VNC server won't have any key layout table configured, so it won't be able to map it to a scancode either.

The only option is to improve the client so it knows how to map the key in question.

**Comment by CendioOssman** [comment] 2017-07-07 10:35
If that was true then no keys would work with the older noVNC (which only sends standard key events), so there must some table loaded. Is there a default "us" table built in?

Does QEMU not have a mode where both standard VNC clients and those with QEMU extensions can coexist?

**Comment by berrange** [comment] 2017-07-07 10:40
Well, ok, yeah it'll fallback to a generic mapping, but that mapping is going to be wrong the majority of users who don't have a us layout keyboard, so that's not a good fallback to rely on. So while you can use a standard VNC client the experience will be awful unless you're physical keyboard is US layout, so we strongly recommend against ever using a VNC client which lacks support for the extended key events.

**Comment by CendioOssman** [comment] 2017-07-07 10:45
Alright. But in the interest of servers that might have fallback tables, I'll update @rfbproto and noVNC to use the standard key event message when the scan code isn't known.

**Comment by berrange** [comment] 2017-07-07 11:05
IMHO such a recommendation is wrong. If QEMU is able to convert to a scancode, and the client cannot, then that is a clear client bug to be fixed. If QEMU is not able to convert to a scancode, then using the standard key event message has no benefit - it just pushes the failure further down the stack, but it still fails.

**Comment by CendioOssman** [comment] 2017-07-07 11:50
Such limitations may not be fixable in the client because they are caused by platform restrictions. This issue here is one such example in the wild.

Another example is a client having both a physical keyboard and a virtual one. The virtual one may not have a direct way of mapping to physical keys of a standard keyboard. The server has a much better chance of knowing the mapping needed to fake physical keys, so sending the symbol from the client makes sense in that case. QEMU might not, but other servers are not in the same situation.

**Comment by CendioOssman** [comment] 2017-07-07 13:16
@steve13814, should be fixed now so update your working copy and clear out your browser cache and you should be fine.

**Closed by CendioOssman** 2017-07-07 13:16 UTC
Labels: bug

**Comment by steve13814** [comment] 2017-07-07 13:41
I can type alphabets now. Thank you.
