### ISSUE TITLE
NO VNC has no right mouse button click equivalent for mobile browser use.

### ISSUE THREAD

**Issue by survivor999** [novnc/noVNC#976] opened 2017-12-12 03:39 UTC
This article link mentions supported browsers for Cloud 9. Mobile Android is not supported.
community.c9.io/t/supported-browsers/1988

This article link explains that mobile browsers do not support right clicking to display
context menus. 

https://android.stackexchange.com/questions/71312/how-to-right-click-in-google-chrome

Cloud 9's ide doesn't appear to have support for mapping mouse keys to keyboard keys.

It seems that NO VNC  would need to offer a key-combination for that.

This may be the Cloud 9 ide's built in browser capability source link,

The cloud 9 built in browser is 

https://saucelabs.com/blog/announcing-cloud9-preview-instantly-preview-your-cloud9-project-in-any-browser-powered-by-sauce-labs

**Comment by samhed** [comment] 2017-12-12 10:33
Duplicate of #972 

Read my response in the issue you opened yesterday please.

**Closed by samhed** 2017-12-12 10:33 UTC
Labels: duplicate, misfiled

**Comment by survivor999** [comment] 2017-12-12 16:06
OK, thanks, I appreciate all the help.
