### ISSUE TITLE
Cursor disappears after mouse click in Edge and Chrome

### ISSUE THREAD

**Issue by CendioNiko** [novnc/noVNC#1300] opened 2019-09-23 15:04 UTC
**Describe the bug**
Mouse disappears after mouseUp in Edge, this bug also affects Chrome but only when using touch devices. It always happens on Edge, even without touch. The cursor reappears as soon as the mouse is moved.

**To Reproduce**
1. Open noVNC in Edge.
2. Connect.
3. Click without mouse movement.
4. Observe mouse not visible.

**Expected behavior**
Expected cursor not to disappear after mouse click.

**Client (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Browser version: 18

**Server (please complete the following information):**
 - noVNC version: master (9886d5951d8f6990cb3a16553a5df482dbcdd68d)
 - VNC server: Tested with both TigerVNC and VMware
 - WebSocket proxy: websockify

**Additional context**
Seemingly only affects platforms that both uses our setCapture() polyfill AND our cursor emulation. This means Edge and most browsers on touch devices as well. But it is harder to reproduce using touch due to the fact that it's hard to lift the finger without also moving the cursor.

Cannot be reproduced on Firefox, Chrome, Safari and IE on any device without touch. Tested the following platforms:

* Windows 10
* macOS 10.14
* Fedora 30
* Chromebook

IE and Firefox both use the built in setCapture() and the cursor emulation is only used on IE, Edge and on any platform with a touch screen.

**Comment by samhed** [comment] 2019-10-17 18:51
We have done an extensive investigation here and the issue is indeed a conflict between our setCapture polyfill and our cursor emulation.
The setCapture polyfill creates an element that covers the entire browser window during a capture, this element is supposed to proxy all wanted events through to the canvas. When the capture ends with a mouseup event, this covering capture element is still up for a brief time. This element goes away when releaseCapture gets called, which, most of the time will come after the mouseup event in the queue.

The problem is that when our new cursor emulation is used it will look at the item under the cursor on mouseup events. This is done in order to determine if a mouse drag ended outside the canvas.

Of course then when both of these are used in conjunction the cursor emulation code will find the covering capture element and conclude that it is NOT the canvas - and thus hide the cursor.

**Comment by samhed** [comment] 2019-10-17 18:53
Aside from the problems in Edge and touch-Chrome, there's an additional related problem in IE:

When using IE with a touch screen, Windows will always hide the mouse cursor after a touch. This is not a behavior that is limited to noVNC - it seems to be a built-in intended behavior in IE.

**Comment by samhed** [comment] 2019-10-21 12:17
Fixed in #1309

**Closed by samhed** 2019-10-21 12:17 UTC
Labels: bug, fixed
