### ISSUE TITLE
I am having error while connecting to localhost

### ISSUE THREAD

**Issue by S4nfs** [novnc/noVNC#1554] opened 2021-05-28 15:39 UTC
Here's my log :
sh: 1: ./apps/noVNC/utils/websockify/run: Permission denied

**Comment by CendioOssman** [comment] 2021-06-07 11:46
Is this a snap? Might be a duplicate of #1527.

**Comment by S4nfs** [comment] 2021-06-07 17:02
I don't know much about this repo. The problem occurs when i reboot my server after the fresh install of novnc.

**Comment by CendioOssman** [comment] 2021-06-08 07:12
How did you install and configure noVNC?

**Comment by S4nfs** [comment] 2021-06-08 16:29
I am using it on my php project which is a control panel to manage virtual machines on KVM based server. I just installed the necessary PHP packages with python installed and nothing else.  i believe its something with the ports as i am not using secure connection and sudo netstat -tulpn | grep 6080  didn't return anything.



Here is the noVNC iframe for users to connect to their vms
![Screenshot (20)](https://user-images.githubusercontent.com/75138345/121221773-85814c80-c8a3-11eb-9a11-814051d2fb55.png)

**Comment by CendioOssman** [comment] 2021-06-09 07:08
I'm afraid that is not a setup we're familiar with so I'm going to have to direct you to whoever did that packaging and see if they can help you. noVNC is just javascript, so anything that has to do with the server setup generally falls outside of this project.

**Closed by CendioOssman** 2021-06-09 07:08 UTC

**Comment by CendioOssman** [comment] 2021-06-17 07:33
If it isn't possible to even download snaps then it seems like there is something generally amiss with your system. I'm afraid that isn't something we can help you out with. I suggest trying the support channels of your distribution.

**Comment by S4nfs** [comment] 2021-06-18 19:18
FIXED:
Ok so the issue is with my file permission on server and not with the snap or any incorrect installation because i use .zip istead of .tar and it resets my files and folder permission which cause thie failed connection error.

**Comment by CendioOssman** [comment] 2021-06-21 06:49
Ah. Glad to hear you found the issue.
