### ISSUE TITLE
Incorrect screen resolutions with the remote resizing option enabled

### ISSUE THREAD

**Issue by AmadeusJpn** [novnc/noVNC#777] opened 2017-02-18 05:19 UTC
Nexus 2013 (1920x1200) / Android 6.0 / the Latest Chrome browser
Tigervnc server 17.01

When accessing with the "Remote Resizing" option, the screen resolution always becomes 960x600 in full screen mode.

**Comment by samhed** [comment] 2017-02-18 14:23
Can not reproduce on Samsung S6 with Android 6.0 with latest chrome and latest tigervnc. Works well for me.

What is running server-side, any desktop environment? Perhaps you have a setting that is causing this?
Does it work for you when connecting from another platform such as Linux or Windows?

If you start Xvnc with "-Log=*:stderr:100" you should be able to see size requests in the Xvnc console output. It should look like this:

> Requested new desktop size: 1920x717

**Comment by AmadeusJpn** [comment] 2017-02-19 03:50
The server is always requested to resize to the half vertically and horizontally as follows:

Sun Feb 19 12:42:48 2017
 XserverDesktop: Got request for framebuffer resize to **960x600**
 XserverDesktop: 1 screen(s)
             0 (0x00000000): 960x600+0+0 (flags
              0x00000000)

**Comment by samhed** [comment] 2017-02-19 19:43
Did you test other platforms?

**Comment by AmadeusJpn** [comment] 2017-02-20 00:30
Yes, I did. I have just found that in some envirnment, the screen scale is set to 2.0, for instance. I haven't tried, yet, but if you changed the scale or the DPI, it would work just fine.

Do you think noVnc needs an option setting that enables us to change the scale factor?

**Comment by CendioOssman** [comment] 2017-02-20 08:39
Right, this is the currently designed behaviour. It's not obvious how to best handle this. You don't want the session to be too tiny. Still, we already have #768 for this so I'll close this as a duplicate of that.

**Closed by CendioOssman** 2017-02-20 08:39 UTC
