### ISSUE TITLE
Crash dialog is blurry on Chrome

### ISSUE THREAD

**Issue by CendioOssman** [novnc/noVNC#1094] opened 2018-06-20 06:51 UTC
The "noVNC has encountered an error" dialog is blurry on Chrome. It seems to be the transform that causes this, so it's an issue we've seen before. We need to find another way of centering the dialog.

Might be an issue on other WebKit browsers as well. Firefox works fine though.

**Comment by samhed** [comment] 2018-10-30 10:11
It seems like this has been fixed in Chrome. I can't reproduce anymore.

I also tested Safari on macOS 10.14, works well there too.

**Closed by samhed** 2018-10-30 10:11 UTC
Labels: bug, fixed, ui/full
