### ISSUE TITLE
the mouse will not be displayed

### ISSUE THREAD

**Issue by QQ2017** [novnc/noVNC#1335] opened 2019-11-27 04:21 UTC
**Describe the bug**
Very good project. When using noVNC to connect tightvnc-2.8.27 (tightvnc server is installed in Win7x64，Chrome run on the win10 1903), the mouse will not be displayed. If you keep moving or clicking the mouse, sometimes the mouse can be displayed. If the mouse pointer changes, such as a hand shape or an input state, the mouse will be displayed immediately. ,Connecting UltraVnc does not have this problem, but UltraVnc uses The experience is not good, Can you fix this problem?

**To Reproduce**
tightvnc server is installed in Windows system

**Expected behavior**
the mouse will not be displayed

**Screenshots**

**Client (please complete the following information):**
 - OS: WinX64
 - Browser: [chrome,IE11,Microsoft Edge]
 - Browser version: [Newest]

**Server (please complete the following information):**
 - noVNC version: [1.1.0]
 - VNC server: [tightvnc-2.8.27 server x32]
 - WebSocket proxy: [websockify]

**Additional context**

**Comment by samhed** [comment] 2019-11-28 11:54
> Connecting UltraVnc does not have this problem

You mean connecting to an UltraVNC server?

Did you try a different VNC client? It is possible that this isn't an issue with noVNC but rather with your TightVNC server.

**Comment by QQ2017** [comment] 2019-11-28 12:08
> > Connecting UltraVnc does not have this problem
> 
> You mean connecting to an UltraVNC server?
> 
> Did you try a different VNC client? It is possible that this isn't an issue with noVNC but rather with your TightVNC server.

I use novnc to connect UltraVNC server and reallyvnc server without this problem, but this problem occurs when connecting tightvnc-2.8.27 server x32.

**Comment by samhed** [comment] 2019-11-28 21:51
Ok, then please test a different VNC client against the TightVNC server pls

**Comment by QQ2017** [comment] 2019-11-29 05:51
> Ok, then please test a different VNC client against the TightVNC server pls

I have tested it and using tightVNC viewer and realvnc viewer to connect tightVNC Server did not have this problem.

**Comment by samhed** [comment] 2019-12-01 22:59
We will need more information then;

Are there any errors in the browser console? Enable debug logging in noVNC and paste the output here.

Could you make a screen recording of the issue?

**Comment by MaitreGuyM** [comment] 2019-12-14 09:59
Hi,

I have the same issues with different servers (TightVNC, OsxVNC).
I only use novnc client and have this bug to. 
The mouse cursor doesn't appear and i have to move it  quickly or change mouse cursor to be displayed.

With other client (tight, tiger...), i haven't this issue.

All other stuf working well. 
My 10cents
Thanks.

**Comment by CendioOssman** [comment] 2019-12-23 15:17
I can reproduce this, and I'm afraid it's a bug in TightVNC. There happens to be bugs in the other clients (at least TigerVNC) that happen to paper over this issue.

The problem is that TightVNC doesn't send over a cursor when you connect. It only sends them when they change. So until the first change you get nothing.

Ideally our "Show dot when no cursor" setting should handle this. I'll see if I can get that running.

**Comment by abulhol** [comment] 2019-12-23 15:22
Hi there, I also have TightVNC server running on W7x64, and the "Show dot when no cursor" setting does help, but only after I have connected to the machine. I.e. if I then activate the dot, I actually see the dot. 
However, if I load noVNC with `show_dot=true` in the GET params, it does not help. 
Is this solvable?

**Comment by CendioOssman** [comment] 2019-12-25 11:05
I hope so. Having a look at it now.

**Comment by CendioOssman** [comment] 2019-12-30 08:32
Initial dot cursor be fixed as of 49db41ea4be69753b5480559839cf031d52a1241.

That is all we'll be doing in noVNC as we consider the main issue to be a bug in TightVNC. It should send a proper cursor on connect and not just when it changes.

**Closed by CendioOssman** 2019-12-30 08:32 UTC

**Comment by abulhol** [comment] 2020-01-08 13:43
The fix works for me, thanks!
