### ISSUE TITLE
keyboard broken in Chrome on Android

### ISSUE THREAD

**Issue by samhed** [novnc/noVNC#822] opened 2017-05-12 15:14 UTC
When using the onscreen keyboard in Chrome on Android, you get a bunch of underscores after each character you type. It's completely broken.

**Comment by CendioOssman** [comment] 2017-05-15 08:05
Works on Chrome book, so it seems to be Android specific.

**Comment by CendioOssman** [comment] 2017-05-15 08:06
Oddly enough this seems to be caused by the modularisation. b56d97524807b125d047730331031ddd00f9c61f works, but 152c399513e250aecda206ce38e2cf934d918c6c is broken. Nothing obvious in the diff why though.

**Comment by CendioOssman** [comment] 2017-05-15 12:46
Fixed in 55988e7aec698e8f23af943fdc268f998fc4eba5.

**Closed by CendioOssman** 2017-05-15 12:46 UTC
Labels: bug
