### ISSUE TITLE
Control Keys Not Working in IE-11

### ISSUE THREAD

**Issue by jeffforbes** [novnc/noVNC#884] opened 2017-08-24 19:10 UTC
We recently discovered and issue with IE11 where the control keys are not working. We can type the username into the VM console, but the enter key has no effect and neither does the backspace key.
The version of noVNC that we are running is from Dec 2016. We tied to use the latest version from github, but we got errors on the tokens used for making the web socket connections, so I had to back out the latest version. We typically use firefox and chrome, so we did not notice when this became a problem. 

Does anyone have any ideas what may be the problem?

**Comment by CendioOssman** [comment] 2017-08-31 13:55
We've done a lot of keyboard fixes lately, so we really need to have you test the latest version.

The token system was removed because it was redundant (and not standardised). You should modify the path element instead with the current code.

**Comment by DirectXMan12** [comment] 2017-09-06 15:20
> The token system was removed because it was redundant (and not standardised). You should modify the path element instead with the current code.

(e.g. `https://your.novnc/vnc.html?path=/websockify?token=XYZ`)

**Comment by CendioOssman** [comment] 2017-09-07 08:08
> (e.g. `https://your.novnc/vnc.html?path=/websockify?token=XYZ`)

Pretty much, but query strings need to be escaped, so:
`https://your.novnc/vnc.html?path=%2Fwebsockify%3Ftoken%3DXYZ`

**Comment by DirectXMan12** [comment] 2017-09-07 13:29
(sssh, I was being lazy ;-) )

**Comment by CendioOssman** [comment] 2017-09-22 13:24
No feedback so assuming it was fixed by using a later commit.

**Closed by CendioOssman** 2017-09-22 13:24 UTC
Labels: bug

**Comment by samhed** [comment] 2017-10-09 15:02
Did a quick test of this while using IE 11 for other tests, and I can't reproduce this keyboard issue. If there ever was one, it seems to be fixed in master.
