### ISSUE TITLE
clipboard error

### ISSUE THREAD

**Issue by StefanHoutzager** [novnc/noVNC#1065] opened 2018-04-24 08:32 UTC
I get this error after pasting a large text in the noVNC clipboard and copy from that clipboard. noVNC clone from about a week ago.

![novnc-error](https://user-images.githubusercontent.com/6817215/39175319-4c03172c-47aa-11e8-9ad0-523a60476dcd.png)

**Comment by samhed** [comment] 2018-04-24 13:40
I can reproduce this issue both in Chrome 65 and in Firefox 59 on Linux.

**Comment by samhed** [comment] 2018-04-24 14:17
The size of the send-buffer is `10240` and in `_encode_message()` we create a new view of the send buffer. The last two arguments to the Uint8Array constructor is the range of the send buffer which we want to use. Trying to send something larger than 10240 bytes won't work with the current code. We need to add some check in the code here.

**Comment by samhed** [comment] 2018-05-04 14:41
Could you please verify that #1074 fixes your issue?

**Comment by StefanHoutzager** [comment] 2018-05-04 14:52
Wow, great! I will test next week and let you know, thanks.
Good weekend, Stefan.

      Van: Samuel Mannehed <notifications@github.com>
 Aan: novnc/noVNC <noVNC@noreply.github.com> 
Cc: Stefan Houtzager <agent_008_nl@yahoo.com>; Author <author@noreply.github.com>
 Verzonden: vrijdag 4 mei 16:41 2018
 Onderwerp: Re: [novnc/noVNC] clipboard error (#1065)
   
Could you please verify that #1074 fixes your issue?—

**Comment by samhed** [comment] 2018-05-07 11:26
#1074 has been merged now, feel free to test the current master.

**Comment by StefanHoutzager** [comment] 2018-05-25 09:47
I tested the clipboard error fix today, but get the error again.
![clipboard](https://user-images.githubusercontent.com/6817215/40538208-544ca02c-6011-11e8-852e-ab8b526d6f42.png)

**Comment by samhed** [comment] 2018-05-25 11:03
That's a new error, how much are you trying to paste?

**Comment by samhed** [comment] 2018-06-07 14:39
I can't reproduce your error, even with an 8MB large paste. Could you upload the file somewhere so I can try with yours? Could you also, in detail, describe the steps you take to get this error?

**Comment by samhed** [comment] 2018-06-08 14:07
Also, which VNC server do you use?

**Comment by StefanHoutzager** [comment] 2018-06-08 15:38
I will find some time next monday for answers. Thanks for your interest!

      Van: Samuel Mannehed <notifications@github.com>
 Aan: novnc/noVNC <noVNC@noreply.github.com> 
Cc: Stefan Houtzager <agent_008_nl@yahoo.com>; Author <author@noreply.github.com>
 Verzonden: vrijdag 8 juni 16:07 2018
 Onderwerp: Re: [novnc/noVNC] clipboard error (#1065)
   
Also, which VNC server do you use?—

**Comment by StefanHoutzager** [comment] 2018-06-11 09:11
Hi Samuel,
Here is the file: https://github.com/formio/ngFormBuilder/blob/master/dist/ngFormBuilder-full.js. I am working in an intellij IDEA code editor. When I press ctrl A to select the file and then ctl C to fill the clipboard I get the error. The server is x11vnc, see the dockerfile where noVNC is added also here: https://github.com/StefanHoutzager/elixir-dev-anywhere-docker

      Van: Samuel Mannehed <notifications@github.com>
 Aan: novnc/noVNC <noVNC@noreply.github.com> 
Cc: Stefan Houtzager <agent_008_nl@yahoo.com>; Author <author@noreply.github.com>
 Verzonden: donderdag 7 juni 16:39 2018
 Onderwerp: Re: [novnc/noVNC] clipboard error (#1065)
   
I can't reproduce your error, even with an 8MB large paste. Could you upload the file somewhere so I can try with yours? Could you also, in detail, describe the steps you take to get this error?—

**Comment by samhed** [comment] 2018-06-11 15:59
oh, so you are actually copying from the remote to trigger the bug instead of pasting. I'll see if I can reproduce. Thanks for the file.

**Comment by samhed** [comment] 2018-06-14 14:52
I could finally reproduce the error with x11vnc and copying from the remote.

**Comment by samhed** [comment] 2018-06-14 15:03
Should be fixed in db9daa9.

Note however that it seems like x11vnc seems to have a limit when it comes to sending large clipboards from the remote:

> 14/06/2018 16:49:20 warning: truncating large PRIMARY/CLIPBOARD selection > 262144 bytes.

Additionally, when x11vnc hits this limit, it has a bug that results in 2-3 characters of junk being placed in the clipboard.

**Closed by samhed** 2018-06-14 15:03 UTC
Labels: bug, fixed, ui/full

**Comment by StefanHoutzager** [comment] 2018-06-14 15:09
Wow, good work, thanks! Can you recommend another server than x11vnc?

      Van: Samuel Mannehed <notifications@github.com>
 Aan: novnc/noVNC <noVNC@noreply.github.com> 
Cc: Stefan Houtzager <agent_008_nl@yahoo.com>; Author <author@noreply.github.com>
 Verzonden: donderdag 14 juni 17:03 2018
 Onderwerp: Re: [novnc/noVNC] clipboard error (#1065)
   
Should be fixed in db9daa9.Note however that it seems like x11vnc seems to have a limit when it comes to sending large clipboards from the remote:
14/06/2018 16:49:20 warning: truncating large PRIMARY/CLIPBOARD selection > 262144 bytes.
Additionally, when x11vnc hits this limit, it has a bug that results in 2-3 characters of junk being placed in the clipboard.—

**Comment by samhed** [comment] 2018-06-14 15:22
I personally like TigerVNC :)

**Comment by StefanHoutzager** [comment] 2018-06-14 15:24
Thanks, I'll see if I can replace x11vnc. Might solve my key repeat issue also.

      Van: Samuel Mannehed <notifications@github.com>
 Aan: novnc/noVNC <noVNC@noreply.github.com> 
Cc: Stefan Houtzager <agent_008_nl@yahoo.com>; Author <author@noreply.github.com>
 Verzonden: donderdag 14 juni 17:22 2018
 Onderwerp: Re: [novnc/noVNC] clipboard error (#1065)
   
I personally like TigerVNC :)—

**Comment by samhed** [comment] 2018-06-15 10:14
Yes, I noticed that annoyingly enough x11vnc runs with keyrepeat disabled as default.. you need to run it with the '-repeat' flag in order to get it working.

**Comment by StefanHoutzager** [comment] 2018-06-15 12:32
Thanks a lot man!

      Van: Samuel Mannehed <notifications@github.com>
 Aan: novnc/noVNC <noVNC@noreply.github.com> 
Cc: Stefan Houtzager <agent_008_nl@yahoo.com>; Author <author@noreply.github.com>
 Verzonden: vrijdag 15 juni 12:15 2018
 Onderwerp: Re: [novnc/noVNC] clipboard error (#1065)
   
Yes, I noticed that annoyingly enough x11vnc runs with keyrepeat disabled as default.. you need to run it with the '-repeat' flag in order to get it working.—
