### ISSUE TITLE
noVNC stopped working in Chrome: Failed to execute 'setItem' on 'Storage' (quota exceeded)

### ISSUE THREAD

**Issue by jankeromnes** [novnc/noVNC#818] opened 2017-05-07 09:30 UTC
On noVNC revisions dating back at least 8 days (April 29 ~13:00 UTC), we're having trouble using noVNC in Chrome (it works fine in Firefox Nightly).

The noVNC screen remains stuck in "Loading" state, and at some point this error shows up in the JS console:

    Uncaught (in promise) Error: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://moz1.janitor.technology/25c1a2605844c62e/8088/<anon1>!raw' exceeded the quota.
      Instantiating https://moz1.janitor.technology/25c1a2605844c62e/8088/<anon1>
      Loading https://moz1.janitor.technology/25c1a2605844c62e/8088/<anon1>
        at browser-es-module-loader.js:249
        at <anonymous>

I believe this is the main bug behind https://github.com/JanitorTechnology/janitor/issues/63, and it still reproduces in `noVNC/master` from 30min ago.

Please let me know if I can do anything to help you investigate / reproduce this issue. Thanks!

**Comment by jankeromnes** [comment] 2017-05-07 09:45
I had a look in Chrome's and Firefox's devtools to see what's taking so much space in local storage, but couldn't find any data apart from cookies. This makes the "exceeded the quota" part somewhat puzzling.

Also the JS error appears to be triggered from /vendor/browser-es-module-loader/src/browser-es-module-loader.js at line 249:

```js
    // evaluate without require, exports and module variables
    // we leave module in for now to allow module.require access
    if (data.key.slice(-8) !== '#nocache') {
        localStorage.setItem(key+'!raw', data.source); // Error happens here, but only in Chrome
        localStorage.setItem(data.key+'!transpiled', data.code);
    }
    (0, eval)(data.code + '\n//# sourceURL=' + data.key + '!transpiled');
    processAnonRegister();
```

**Comment by samhed** [comment] 2017-05-08 06:12
Can't reproduce using noVNC/master in Chrome 58.

What version of Chrome do you use? Can you reproduce on multiple devices? Perhaps its a setting in your Chrome profile?

**Comment by jankeromnes** [comment] 2017-05-10 21:34
@samhed thanks a lot for trying! I use Chrome `58.0.3029.96` and Firefox `55.0a1`.

I was able to bisect through noVNC's history to find which commit started breaking things for me:

- Note: on earlier commits I found `Uncaught SyntaxError: Unexpected token export` or `import` problems, and then 404 errors on `node_modules/browser-es-module-loader/dist/babel-browser-build.js` and `browser-es-module-loader.js`, but the 404s were resolved by running `npm install` in the noVNC directory.
- e25f9c40102c6566e63b7caa30f620da86fd0d60 was the last working commit for me (noVNC displays the "Connect" button, and it works)
- 399fa2ee2da4b7a766e7b95b56436e79f0a42a73 shows the first occurence of:

    browser-es-module-loader.js:80
    Uncaught (in promise) Error: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://moz1.janitor.technology/62ae913ebed04207/8088/app/ui.js!raw' exceeded the quota.
      Instantiating https://moz1.janitor.technology/62ae913ebed04207/8088/app/ui.js
      Loading https://moz1.janitor.technology/62ae913ebed04207/8088/app/ui.js
        at browser-es-module-loader.js:1364
        at <anonymous>

before displaying any "Connect" button (the loading spinner goes on forever and I can never use VNC). This fails only in Chrome, but works fine in Firefox Nightly.

@DirectXMan12 since you authored this commit, do you have any idea what could be going wrong on my setup?

**Comment by DirectXMan12** [comment] 2017-05-11 19:27
So, it looks like Babel is try to compile and store a very large JS file (it looks like one that's external to noVNC -- from your project). We recently switched to using ES6 modules, and because module-loading support in the browsers is not quite there yet, we use a shim to compile the modules to SystemJS on the fly when using un-compiled noVNC. The shim caches the compiled files for faster dev turnaround.

We expressly do not reccomend using the uncompiled form of noVNC in production, since running Babel in the browser is not recommended for production.. Instead, you should include a copy that's first been converted from ES6 modules to SystemJS, CommonJS, RequireJS, etc. There's a tool in the utils directory (utils/use_require.js) which will do this for you.

**Comment by jankeromnes** [comment] 2017-05-12 11:02
Thanks a lot for your reply @DirectXMan12!

> So, it looks like Babel is try to compile and store a very large JS file (it looks like one that's external to noVNC -- from your project).

Actually, the logs in https://github.com/novnc/noVNC/issues/818#issuecomment-300619377 seem to point to noVNC's `/app/ui.js` file.

> We expressly do not reccomend using the uncompiled form of noVNC in production, since running Babel in the browser is not recommended for production.

I install and set up noVNC using your README.md's [quick start](https://github.com/novnc/noVNC#quick-start) instructions, i.e. by [cloning it from GitHub](https://github.com/JanitorTechnology/dockerfiles/blob/cefd6492ae95f47a2d95e6368ea7c56740342895/ubuntu-dev/ubuntu-dev.dockerfile#L171-L173) and then [running its launch.sh script](https://github.com/JanitorTechnology/dockerfiles/blob/cefd6492ae95f47a2d95e6368ea7c56740342895/ubuntu-dev/supervisord.conf#L18-L20). If this is not the recommended way to run noVNC in production, could you please mention in README.md how to compile noVNC for production?

I will now try to find out how to use `/utils/use_require.js` to build and serve a production-grade noVNC in my system. Thanks for pointing me to this script! If helpful, I can post back here with the steps I found so that they can be documented in the README.md.

**Comment by jankeromnes** [comment] 2017-05-12 11:14
Follow-up: In `package.json`'s `prepublish` step, I found that I could use `node ./utils/use_require.js --as commonjs` to write many CommonJS files into `/lib`. Now I need to figure out how to point `/vnc.html` or `/vnc_auto.html` (renamed to `/vnc_lite.html` 4h ago) to the compiled files instead of using Babel.

**Comment by jankeromnes** [comment] 2017-05-15 08:05
Note: This is actually not a Chrome-only issue, because it started happening in Firefox Nightly too:

    browser-es-module-loader.js:80:
    Error: Persistent storage maximum size reached
      Instantiating https://moz1.janitor.technology/4ddccaa36314e370/8088/core/rfb.js
      Loading https://moz1.janitor.technology/4ddccaa36314e370/8088/<anon1>
      Loading https://moz1.janitor.technology/4ddccaa36314e370/8088/<anon1>

**Comment by CendioOssman** [comment] 2017-05-15 08:18
Found a clue here:

https://support.mozilla.org/en-US/questions/963825

It seems like the quota is shared, so it might be other things filling up the local storage.

**Comment by jankeromnes** [comment] 2017-05-15 08:22
> We probably shouldn't crash if we can't cache things. It is only a cache after all.

I definitely agree.

> Are you testing in private/incognito mode?

I'm not testing in private/incognito mode, but I can try that if it helps.

I just tried inspecting Local Storage with the browser devtools again, and this time Chrome was able to list (many) cache entries. I believe the reason my service hits cache limits is that we serve many noVNC front-ends (from as many development containers on moz1.janitor.technology) but all from the same root domain, and Babel seems to store all raw+transpiled versions of noVNC front-end files several times until the quota is exceeded.

**Comment by DirectXMan12** [comment] 2017-05-15 16:22
> If this is not the recommended way to run noVNC in production, could you please mention in README.md how to compile noVNC for production?

Yeah, sorry about that, that change is somewhat recent, and I haven't fully updated the docs to indicate it yet.

> Actually, the logs in #818 (comment) seem to point to noVNC's /app/ui.js file.

Whoops, my bad :-).

**Comment by jankeromnes** [comment] 2017-05-15 16:51
> Yeah, sorry about that, that change is somewhat recent, and I haven't fully updated the docs to indicate it yet.

No worries! Could you please point me in the right direction? If I can get a full noVNC production build, I can help you by documenting

**Comment by jankeromnes** [comment] 2017-05-15 16:52
(I accidentally closed the issue, sorry about that.)

**Comment by CendioOssman** [comment] 2017-05-16 12:10
Fixed in 777df7c274222806b5d66412058cabf71f5d4ca7.

I also tried to implement hashing for cache management, but the whole rollup/browserify thing was being difficult so that didn't make the cut.

Sharing the cache between the instances is not easily done as the different instances might run different versions. So it would need a different cache strategy. For now you'll have to pre-process the files, or change the design so that a shared copy of noVNC is used.

**Closed by CendioOssman** 2017-05-16 12:10 UTC

**Comment by jankeromnes** [comment] 2017-05-16 12:46
Thanks a lot @CendioOssman!

@DirectXMan12 Could you please point me in the right direction regarding running a production noVNC build based on the files that `./utils/use_require.js` puts in `./lib`? (How do I `launch.sh`, and which `vnc.html` should I serve?) Many thanks!

**Comment by CendioOssman** [comment] 2017-05-16 13:00
E.g.:

```
$ ./utils/use_require.js --as amd --with-app
```

The script will generate a new structure for you under `build/`, including a modified `vnc.html`.

Note that you generally need to provide the module loader script by hand. In this case you need to pay attention to this line in the output:

```
Please place RequireJS in /home/ossman/devel/noVNC/build/require.js
```

**Comment by jankeromnes** [comment] 2017-05-16 14:45
@CendioOssman Great, thanks a lot! `--with-app` did the trick. Note: It seems that using `commonjs` instead of `amd` doesn't require the manual step you mention:

```bash
node ./utils/use_require.js --as commonjs --with-app
```

**Comment by DirectXMan12** [comment] 2017-05-16 19:14
> I also tried to implement hashing for cache management, but the whole rollup/browserify thing was being difficult so that didn't make the cut.

Yeah, I looked into doing that but there were a couple of complicating factors that didn't really make it worth it (among other things, actually computing the hash in the browser seemed more effort that was worth).

> It seems that using commonjs instead of amd doesn't require the manual step you mention:

Yes, CommonJS will produce an app using a browserify blob (so you don't actually need the rest of the generated files -- just `app.js`).
