### ISSUE TITLE
NoVNC does not open in iFrame

### ISSUE THREAD

**Issue by clemlaplace** [novnc/noVNC#1636] opened 2022-03-23 15:59 UTC
Hello,

I am fairly new to iframe & noVNC, I am running a software on noVNC and it works as expected on a new window.
However, when I run the following line I get a white space.

<iframe id="vnc" src="http://18.198.179.8:6080/vnc.html?host=18.198.179.8&port=6080" width="825px" height="635px"></iframe>

Thank you for the help

**Comment by logan-webGL-openGL** [comment] 2022-03-23 17:36
turn on 3rd party cookies on your web browser

**Comment by clemlaplace** [comment] 2022-03-24 10:40
Thabk you for the quick answer.
However, 3rd party cookies were already turned on, so it did not do the trick.

Do you have other potential solutions ?

Thanks

**Comment by logan-webGL-openGL** [comment] 2022-03-24 10:56
i will test this on my computer.

**Comment by CendioOssman** [comment] 2022-03-24 12:18
Please also fill out the complete bug form.

Have you checked the browser console for errors?

**Comment by clemlaplace** [comment] 2022-03-24 13:39
I believe the problem comes from my non encrypted adress, as suggested in the browser console errors:

"Mixed Content: The page at 'https://inventeeth.bubbleapps.io/version-test/test?debug_mode=true' was loaded over HTTPS, but requested an insecure frame 'http://18.198.179.8:6080/vnc.html?host=18.198.179.8&port=6080'. This request has been blocked; the content must be served over HTTPS."

I will try to fix this issue. Do you have any documentation on how to encrypt noVNC ?

Thank you for the help

**Comment by CendioOssman** [comment] 2022-03-24 13:42
It depends entirely on the web server you are using for noVNC. If it's websockify it has information here:

https://github.com/novnc/websockify/wiki/Encrypted-Connections

**Comment by CendioOssman** [comment] 2022-03-24 13:42
I'll go ahead and close this issue as the cause seems to have been identified.

**Closed by CendioOssman** 2022-03-24 13:42 UTC
