### ISSUE TITLE
When is 1.0 Planned?

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [novnc/noVNC#987] opened 2018-01-06 16:25 UTC
When is 1.0 planned to be released?

**Comment by samhed** [comment] 2018-01-08 23:35
See the milestone here: https://github.com/novnc/noVNC/milestone/2

only known thing remaining outside of practical release work is #974 

Closing due to duplicate of #889

**Closed by samhed** 2018-01-08 23:36 UTC
