### ISSUE TITLE
cloud9 + noVNC: cant see any windows that open

### ISSUE THREAD

**Issue by i95swervin** [novnc/noVNC#744] opened 2017-01-08 05:14 UTC
Hello,

 I recently installed novnc on cloud9, It was working flawless until I re installed and got the newest version of novnc. Now when I log in I cannot see any of the windows that I open just the bottom half of everything all the windows are stuck up at the top. i.e terminal, top, firefox etc. Is there a old version I can download? until this gets figured out? here is a screen shot of what I mean.
![screenshot from 2017-01-08 00-12-38111111111111111](https://cloud.githubusercontent.com/assets/20628439/21747573/624177ee-d538-11e6-885e-ac79200d40f8.png)

**Comment by samhed** [comment] 2017-01-08 18:30
Just use git to check out an old release.

However, I assume cloud9 uses x11vnc? This looks like an issue we have seen before with noVNC and x11vnc run with the option "-ncache".

**Comment by CendioOssman** [comment] 2017-02-02 09:15
I've seen this with TigerVNC as well. I suspect it was caused by 47fbdced4530dd2a66a5f20be27b69d6c12a6ffc. Will have to investigate more.

**Comment by CendioOssman** [comment] 2017-02-03 12:20
Fixed in 9865432a027e0ee5461ef1c5d93dd11a40a804e0.

**Closed by CendioOssman** 2017-02-03 12:20 UTC
Labels: bug
