### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data' of null

### ISSUE THREAD

**Issue by zqwlai** [novnc/noVNC#969] opened 2017-12-07 10:29 UTC
TypeError: Cannot read property 'data' of null
    at Display.startTile (http://10.20.0.10:6080/core/display.js!transpiled:414:42)
    at RFB.HEXTILE (http://10.20.0.10:6080/core/rfb.js!transpiled:2032:43)
    at RFB._framebufferUpdate (http://10.20.0.10:6080/core/rfb.js!transpiled:1468:68)
    at RFB._normal_msg (http://10.20.0.10:6080/core/rfb.js!transpiled:1354:44)
    at RFB._handle_message (http://10.20.0.10:6080/core/rfb.js!transpiled:632:43)
    at Websock._recv_message (http://10.20.0.10:6080/core/websock.js!transpiled:322:45)

I can connect to virtual server by VNC Viewer, but it shows this error when I connect that by nonvc,, Can anybody help me?

**Comment by samhed** [comment] 2017-12-07 11:15
duplicate of #965

**Comment by CendioOssman** [comment] 2017-12-07 11:15
Why is everybode getting hit by this now? This bug has been in the code for years.

What have you started doing differently? :)

**Closed by samhed** 2017-12-07 11:15 UTC
Labels: duplicate
