### ISSUE TITLE
Connecting to Intel AMT fails

### ISSUE THREAD

**Issue by grepaly** [novnc/noVNC#860] opened 2017-07-15 09:37 UTC
Dear All,

is there a trick to connect to Intel AMT? What i see on the server side is: "handler exception: [Errno 107] Transport endpoint is not connected". On the browser side: Server native red-shift is not 16 (warning) and WebSocket on-close event. It does ask for the password and it says disconnected.

**Comment by CendioOssman** [comment] 2017-07-21 12:37
Those kind of servers generally don't fully support the VNC protocol, so I would suspect it kicks out noVNC when it asks for a different pixel format. Have you tried some other VNC clients?

**Comment by DirectXMan12** [comment] 2017-07-21 15:51
Yeah, noVNC tends to be a bit strict with the pixel formats that it supports, for performance reasons (because most "normal" VNC servers use one or two different ones, so we can get away with it).  I believe the iKVM support PR expands this support a bit, so you might want to try with that branch (see #614 and friends).

**Comment by haqa** [comment] 2017-07-25 14:53
If you go back to v0.6.2 it works fine. I suspect a more recent change is incompatible with the AMT VNC KVM Redirector.

**Comment by DirectXMan12** [comment] 2017-07-26 14:02
huh, if that's the the case, then it's a regression.  Do you think you could send us a recording (run websockify with the `--record` option) so that we could track it down?

**Comment by haqa** [comment] 2017-08-08 14:55
Regrettably I'm not allowed to do that (This is being used within a corporate environment). If I can get access to an AMT device outside of work I'll post a dump here.

**Comment by kimsto** [comment] 2017-08-14 11:50
I think this is directly related to removing colormap support in commit 26586b9.
This removed the explicit test for AMT to disable true_color mode:
if (this._true_color && this._fb_name === "Intel(r) AMT KVM") {

**Comment by CendioOssman** [comment] 2017-08-14 15:09
Well that is annoying. So the question is do we want to fix and keep all that colour map code just to support Intel AMT? (which is technically in violation of the VNC protocol by doing this)

Does this happen on current systems as well, or just older ones?

TigerVNC has also dropped colour map support, so which client to people normally use for these systems?

**Comment by DirectXMan12** [comment] 2017-08-17 15:25
looks like there are still a few color map servers floating around these days.  We might have to re-implement that support (see also #882)

**Comment by haqa** [comment] 2017-08-22 09:10
My personal feeling is that removing compatibility with hardware implementations of the server is just making peoples lives hard.

Oracle (and then Chrome and Firefox) did this with Java and overnight hundreds of thousands of DRAC and iLO servers became inaccessible.

The strength and power of Open Source projects such as this is that they are run by people who know doing this is a bad thing, and so don't.

(Just my opinion)

**Comment by CendioOssman** [comment] 2017-08-23 07:51
Unfortunately we only have so much time we can devote to developing noVNC, so we are always looking for things to remove in order to free up time. The colour map support is supposed to be optional and was causing annoying complexity in our code. Ideally Intel should fix this as it is really a bug in their code. But I suspect they don't really care and probably have their own client rather than trying to truly by VNC compatible...

I can have a look and see if we can support these things in a way that doesn't mess things up too badly. But I need to find a machine that has this feature first...

**Comment by haqa** [comment] 2017-08-23 15:29
I do understand, there are only so many open-source hours in the day (Many of my own projects are suffering from that shortage too), I'm just pointing out that as the mainstream VNC clients drop colour map support, the unfortunate people (such as me, currently with around 1000 Intel NUCs to manage, soon to double) with these devices are slowly running out of options, and until recently noVNC has been their lifeline. Realistically Intel isn't going to fix its code, not because they have a viable client (they don't) but because the really don't particularly care.

I'll see if I can do anything to help out.

**Comment by CendioOssman** [comment] 2017-08-28 10:31
Apparently we don't have any machines with AMT that I can use here. Is it possible for you to set one up that I can access?

**Comment by CendioOssman** [comment] 2017-09-08 09:27
Could you guys test the PR I just added and see if that works with your machines? It is just a guess since I don't have anything to test with.

**Comment by samhed** [comment] 2017-09-27 13:39
@grepaly @haqa @kimsto Could you please test #893 so that we can confirm that it fixes your issue? We would like to merge and wrap up a noVNC release.

**Comment by grepaly** [comment] 2017-09-27 17:25
Sure I will. I will be out of office for the next few days but early next
week I will test.

Thanks for all the efforts!

A.

**Comment by samhed** [comment] 2017-10-05 12:22
@grepaly @haqa @kimsto we would like to push a 1.0 release of noVNC as soon as possible and this is the remaining blocker.

If it is important for you that these devices work with noVNC I would like to ask you test the fix we have suggested in #893 very soon. If you won't prioritize testing this, maybe it's not so important to add support after all? :wink:

**Comment by samhed** [comment] 2017-10-05 15:00
Fix merged in #893

**Closed by samhed** 2017-10-05 15:00 UTC
Labels: bug, regression
