### ISSUE TITLE
Shouldn't scroll with focusOnClick

### ISSUE THREAD

**Issue by lilyhoratio** [novnc/noVNC#1569] opened 2021-08-02 19:23 UTC
The `focusOnClick` option being enabled by default currently scrolls the VNC into view when the VNC is clicked.  It would be nice to have an option to [prevent scroll](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) when the VNC is focused.

**Comment by samhed** [comment] 2021-08-04 13:03
It sounds like you actually want to disable `focusOnClick`? In what scenario do you want focus but not scroll?

**Comment by CendioOssman** [comment] 2021-08-13 12:59
Probably need some testing, but it sounds like `preventScroll` should be the default. If we get a click then obviously some part of the display is visible. And I don't think any browser scrolls when an input fields gets focus on a clock (which is the behaviour we try to mimic).

(on the same note we should add the `options` parameter to `RFB.focus()` as that should be a clone of `HTMLElement.focus()`)

**Comment by CendioOssman** [comment] 2021-11-11 09:25
I'm unable to reproduce an issue here. Can you share you test scenario?

**Comment by lilacdev** [comment] 2021-11-12 08:20
Hi guys,

I am unable to send a reproduction test, but I can confirm this issue. I looked at the code some time ago to propose a PR by using `RFB.focusOnClick = false;`, but it has not effect, even when forcing it inside library.

This issue appears when canvas is larger than parent div.

This behaviour is pretty well explained here : https://stackoverflow.com/questions/48603670/how-to-prevent-scroll-when-clicking-on-html-canvas-for-the-first-time .

**Comment by CendioOssman** [comment] 2021-11-12 15:44
Ah. It only seems to happen with Chrome. Firefox doesn't have any such odd behaviour.

**Comment by CendioOssman** [comment] 2021-11-16 08:40
Fixed in 301714928bfd45a0f11d8cbaec8f9fe538cefe79. Thanks for reporting!

**Closed by CendioOssman** 2021-11-16 08:40 UTC
Labels: bug, patchwelcome

**Comment by CendioOssman** [comment] 2021-11-29 13:58
We now publish development versions of noVNC on npm. Switch over to the dev tag and you'll get the absolutely latest code. Note that this code will have a higher risk of bugs though.

**Comment by lilacdev** [comment] 2021-11-29 13:59
Great! Many thanks !
