### ISSUE TITLE
CheckBox on ControlBar show on Chrome

### ISSUE THREAD

**Issue by al3x609** [novnc/noVNC#1088] opened 2018-06-09 01:19 UTC
**Describe the bug**
 Fail show checkbox Controlbar

**Expected behavior**
Expected that show always
**Screenshots**
![image](https://user-images.githubusercontent.com/4086644/41186247-fce55e3e-6b58-11e8-8d4b-da9980935a79.png)

**Client (please complete the following information):**
 - OS: MacOS 10.14 beta 1
 - Browser: Google Chrome 
 - Browser version: 67.0.3396.79

**Server (please complete the following information):**
 - noVNC version: 1.0.0
 - VNC server: without vnc server
 - WebSocket proxy: websockify

**Comment by samhed** [comment] 2018-06-10 09:32
Can't reproduce on Chrome 66 on Linux, perhaps it's a chrome 67 thing or a macOS thing.

Does it seem like the checkboxes are there but just not showing? Does clicking the labels, for example "View Only" have any effect?

**Comment by al3x609** [comment] 2018-06-11 17:10
yes, the checkboxes there are there, and "View Only" have the effect expected, but for any reason no I see  de box.

**Comment by al3x609** [comment] 2018-06-11 17:28
maybe a css issue  for chrome, I don't have linux, but I can run a "Centos 7.5 docker container" and the fail are there too.   One more thing, on the same browser session, when I change the Responsive Design Mode in the Developer tools, the bug no exist more.

this is my implementation test... ( the bug exist in 
unmodified version too)

![image](https://user-images.githubusercontent.com/4086644/41246983-445150fa-6d72-11e8-816b-1a77c84c1dfa.png)

Sorry for my poor english.

**Comment by samhed** [comment] 2018-06-13 11:39
I can't reproduce the issue on Chrome 67 on macOS 10.13.

But you said you are running a 10.14 beta. I don't have a 10.14 machine available for testing at the moment. Can you try some other webpage that uses checkboxes to verify that it's a general issue? Beta versions are much more likely to have bugs so to me it's very likely that your issue will be fixed by Apple somewhere along the line.

**Comment by al3x609** [comment] 2018-06-15 06:18
thans, this is a bug on this chrome version.  the others browsers work fine.

**Closed** 2018-06-15 06:18 UTC
Labels: bug, ui/full
