### ISSUE TITLE
IE and Edge unusable - Pressing SPACE toggles UI buttons

### ISSUE THREAD

**Issue by samhed** [novnc/noVNC#692] opened 2016-10-19 14:35 UTC
After you have used any button in the control bar SPACE will, when pressed, toggle that button. It continues to happen even after you have used the mouse inside the VNC screen. It only stops happening if you click somewhere outside any button in the UI, or if you click on any element that belongs to the browser GUI.

Even though the SPACE is being sent to the server, the toolbar buttons are still being toggled. For example, if the button you most recently pressed was "connect" and you want to send a SPACE to the server, you will disconnect. This is a horrible experience as you might imagine and I am extremely surprised that we haven't had anyone reporting this before.

Found using IE 11 and Edge 38 on Windows 10. Can reproduce using both using code from 2 years ago and with the current master with the new UI, so this is not a regression in noVNC.

**Comment by samhed** [comment] 2016-10-19 14:37
Quick tests seem to indicate that this does not happen on Windows 10 mobile. It does however happen both on a microsoft surface device with a touch screen, and on a computer without touch screen.

**Comment by geocode** [comment] 2016-11-02 17:09
I am seeing a somewhat similar issue with F10 and firefox.  In some but not all instances of firefox (we have not been able to come up with a consistent work around).  F10 will display the firefox menu instead of sending F10 to the application on the other end of the vnc connection.  Sometimes it works, sometimes it doesn't.  Does this sound like it is caused by the same issue that is scheduled for v0.7.0?  Any help on this would be greatly appreciated!

**Comment by samhed** [comment] 2016-11-03 07:43
> Does this sound like it is caused by the same issue that is scheduled for v0.7.0?

No, not at all

**Comment by samhed** [comment] 2017-03-14 12:04
I have no direct idea for how to work around this. I propose to remove this from the 0.7 milestone.

**Comment by samhed** [comment] 2017-05-09 09:04
This is not a regression, it's been like this for ages. Fixing this will likely require some major rethinking of focus handling. Let's postpone this.

**Comment by samhed** [comment] 2017-10-09 14:52
Note that with master I can still reproduce the issue on Edge but not on IE. I used private browsing and inspected the code to make sure IE was running master and it sure seems like the issue doesn't exist on IE anymore.

Anyway, still a problem on Edge, and #916 fixes it!

**Comment by CendioOssman** [comment] 2017-10-18 13:15
Fixed by #916.

**Closed by CendioOssman** 2017-10-18 13:15 UTC
Labels: bug
