### ISSUE TITLE
repaint bugs/stalls for certain platform combinations (noVNC 1.0.0 via Open OnDemand)

### ISSUE THREAD

**Issue by michaelkarlcoleman** [novnc/noVNC#1175] opened 2018-12-12 20:58 UTC
**Describe the bug**
The VNC connection happens, and the initial desktop is drawn.  On bad platforms, repainting soon stops, though it can be partially kicked to happen by (for example) grabbing a terminal window and moving it around.  Once the moving stops, repainting still does not happen.  This is not a complete solution, in that not everything in the VNC window gets updated, even if the terminal window is moved around the entire VNC window.  Basically, the failed configurations are unusable.

Mysteriously, this only fails on some platforms.  I've tried maybe ten or twelve combinations on five laptops.  All with very recent versions of browsers and updated OSes.  Patterns observed so far:
1.  If either browser (Chrome or Firefox) works on a machine, they both do.  Otherwise they both fail.  Even tried Android Firefox on the failing Chromebook, and it fails the same way.
2.  The two laptops that are failing are "older", bought two or three years ago.  The working ones are all newer, about a year or less old.  (The failing Chromebook is a first-generation Pixel, and still pretty snappy.  The working Chromebook is cheap and slow, but does have a newer hardware config (e.g., it supports the new Linux container feature).)
3.  I'm seeing different results on two Chromebooks running exactly the same software version.  One works, one fails.
4.  The results are completely deterministic.  For a given config, always succeeds or always fails.
5.  If I make a session fail, with a bad platform, I can reconnect to the same session with a good platform and the failure continues.  Apparently there is state in Xvnc (or websockify?) that "remembers" the failure.
6.  Conversely, if I start a session on a good platform, disconnect, and reconnect with a bad platform, updating starts failing, as before.

Given points 2 and 3, I'm inclined to suspect that somehow hardware matters.  Baffled as to why that would be.

I've also reproduced a failure without touching the keyboard, by doing things with the mouse.

Note that this VNC is started and served by Open OnDemand.  Doubt this matters, though.

**To Reproduce**
1. Start mate session.
2. Open a terminal.
3. Type "top" and return.
4. Typically only one or two letters is echoed, then no further repaint.  (At this point, if the terminal is moved around with the mouse, updates occur and we can see that 'top' is running.)

**Expected behavior**
Generally, updates should always happen, perhaps subject to latency and bandwidth.

**Screenshots**
Skipping.

**Client (please complete the following information):**
(see below)

**Server (please complete the following information):**
 - noVNC version: 1.0.0 vendored into ondemand rpm `ondemand-1.3.7-2.el7.x86_64`
 - VNC server: `turbovnc-2.2-20180927.x86_64` (from turbovnc repo)
 - WebSocket proxy: `websockify 0.8.0` (installed via pip)

**Additional context**
Here's some raw data on experiments.  (Probably correct, but maybe some typos.)

Good platforms:
- ASUS Chromebook C202SA-YS02, Chrome 70.0.03538.110
- Windows 10 (Dell, 11 months old), Chrome 71.0.3578.80, Firefox (latest)
- Macbook (13 months old), Chrome and Firefox (latest, version unknown)

Bad platforms:
- Google Pixel (2015 version?), Chrome 71.0.03578.85  (probably from beta channel?)
- Google Pixel (2015 version?), Chrome 70.0.03538.110, also Android Firefox (latest, version unknown)
- Windows 10 laptop (Lenovo, several years old), Chrome 71.0.3578.80, also Firefox (latest, version unknown)

Some of these tried only at home or work, but some fail in both locations.  Have not seen any variation in behavior for a given laptop by location.

**Comment by samhed** [comment] 2018-12-12 23:05
> VNC server: turbovnc-2.2-20180927.x86_64

Have you seen if you can reproduce the issue with a different VNC client connecting to the same server?

**Comment by michaelkarlcoleman** [comment] 2018-12-12 23:41
@samhed It'd be relatively involved to test exactly, but installing realvnc.com's VNC Viewer for Google Chrome, and hitting a turbovnc server installed from that same rpm, the problem does not occur.  This is with a "bad" Chromebook.

The scenario is a bit different in that we're not passing through the websockify part here--it's just a direct connection.  Also, in this case it's not a mate session, but just a bare-bones session showing an xterm window.  But I'm able to run 'top' and have it work correctly.

**Comment by michaelkarlcoleman** [comment] 2018-12-13 04:53
Is there a VNC protocol analyzer?  Or does anyone know what flags/etc could be flipped in the Xvnc server to get it to stop sending updates for changed regions?

**Comment by CendioOssman** [comment] 2019-01-11 13:33
Not really. VNC is a bit of a pain trying to sniff, so I'm not aware of any reliable analyzer.

Let's try to figure out if this is a network issue or a graphics issue.

First off, have you tried connecting the bad laptops via ethernet cable? Perhaps it is some wifi issue.

Second, instead of moving the terminal could you try just moving the mouse around and see if that gets the updates flowing. Also try triggering small graphical changes, e.g. moving the cursor across a button so it keeps changing appearance.

**Comment by CendioOssman** [comment] 2019-01-11 13:35
Also, if you could try a setup with a different VNC server then that would also be helpful in pinpointing this.

**Comment by michaelkarlcoleman** [comment] 2019-01-16 22:32
Unfortunately, neither bad laptop has an ethernet port.  It's hard to imagine networking being an issue with the bad Chromebook, though, as I've been using it as a primary machine for several years, both web browsing and SSH with the Chrome extension.  I've not observed any flakiness.  And presumably all of this is passing over a TCP connection.  I could barely imagine a scenario involving a subtle difference in latency and/or how and when push packets get sent, but that sure sounds unlikely.

I'll try to look at this later, but I'm pretty sure merely moving the mouse around doesn't lead to updates by itself.  Not sure about the case of moving over a GUI element.

**Comment by CendioOssman** [comment] 2019-01-18 15:44
When you get imperfect updates, are there "older" areas that remain in the bad state? Or is there a strict ordering to updates?

Do you think you could get a screen video capture of this?

**Comment by michaelkarlcoleman** [comment] 2019-01-18 20:32
@CendioOssman Here's an attempt at a video.  Unfortunately, it's hard to tell exactly when I'm mousing down and up, but it gives the general idea.  And indeed I did notice that merely waving the mouse over a GUI element does sometimes cause an update (of the terminal running `top`).

https://drive.google.com/file/d/1BqPZ44dCoqr4mS2RZ74tGPKVlui0wlkx/view?usp=sharing

**Comment by CendioOssman** [comment] 2019-01-21 11:40
Alright, so the video cleary shows that this is not a network issue. You can tell by the fact that updates are not getting "flushed" and you get updates that are essentially out of order. The only way that can happen is if the server or client somehow misses some update. The network can never drop them as that would cause a disconnect.

You wrote:

> 5. If I make a session fail, with a bad platform, I can reconnect to the same session with a good platform and the failure continues.  Apparently there is state in Xvnc (or websockify?) that "remembers" the failure.

That would strongly indicate that the problem is not in the client, but rather in the server. It would seem only some clients are able to provoke the bug though.

So I would really like you to try your setup with a different server, e.g. TigerVNC. If it doesn't show up there then I would suggest to file a bug with TurboVNC and see if they can debug why it seems their server drops some updates.

**Comment by michaelkarlcoleman** [comment] 2019-01-21 21:02
I think your analysis makes sense.  In order to blame noVNC, we'd have to construct a scenario where it is sending illegal VNC traffic, and the server is not protecting itself from it (at least as far as aborting with a diagnostic).  This does sound pretty unlikely.

It is rather mystifying that the same version of the same browser can work or fail depending (apparently) on the specifics of the hardware.  But that's not consistent with the problem ultimately being in TurboVNC server code.

I'll see what I can do about debugging the server end.

**Comment by CendioOssman** [comment] 2019-02-15 09:44
Closing this for now. Please let us know if more details arise.

**Closed by CendioOssman** 2019-02-15 09:44 UTC

**Comment by michaelkarlcoleman** [comment] 2019-02-18 03:53
Sounds fine.  Unfortunately I don't have the cycles to pursue it further right now, and with any luck, perhaps this only happens with old hardware and/or due to some local oddity.
