### ISSUE TITLE
Chrome 77 memory leak

### ISSUE THREAD

**Issue by gicuuu3** [novnc/noVNC#1302] opened 2019-09-30 09:38 UTC
**Describe the bug**

In Chrome 77(and 78), when running noVnc on a canvas object, if we switch to a different browser tab memory stops being garbage collected and fills up to the brim(graphics memory and then system ram).

**To Reproduce**

1. Access www.demodesk.com/manage
2. Create a free account
3. Start a demo(Via Meet Now button)
4. Share more => local desktop => share local desktop
5. Inspect memory consumption(disabling hardware acceleration helps visualize the problem since the graphics card memory will not be touched)

**Expected behavior**
The memory used should drop every couple of seconds(garbage collected)

**Client (please complete the following information):**
 - OS: Mint 18.2(Linux 4.8.0-53-generic x86_64)
 - Browser: Chrome
 - Browser version: 77 & 78

**Server (please complete the following information):**
 - noVNC version: commit id: 8acadd9e972b72eb5667e397c9dac07feca78949
 - VNC server: TigerVNC
 - WebSocket proxy: websockify

**Additional context**

I'm aware that this is exclusively a Chrome issues(since Chrome 76 worked perfectly fine), but I'm filing in case it helps narrow down the problem.

This seems to happen if the canvas is not being directly visualized(either running in a different tab or being set do `display: none`)

I've also tested on the latest release of noVNC, **1.1.0**, and the issue persisted.

Firefox does not seem to have this problem.

I've been able to also reproduce it on a Mac system.

-------------------
P.S. Thanks a lot for the noVNC project. It's awesome what you guys managed to do.

I'll appreciate any help or input into this issue. Thank you for your time!

**Comment by samhed** [comment] 2019-10-01 20:09
I've followed your instructions (not sure why they included "share local desktop" however since that has nothing to do with noVNC) but I can't reproduce the issue. 

I used chrome's built-in memory consumption monitor and ran with disabled hardware acceleration.

What kind of numbers are you seeing?

**Comment by gicuuu3** [comment] 2019-10-01 20:37
I mentioned _Local desktop sharing_ because it creates the perfect scenario to see the effects. But, I realized later that it's a privacy concern for people to share their screen. My bad.

There's another way to prove it:

- Open a youtube video in the internal browser
- Switch to a different tab in the external one

I've added a youtube video that shows the behavior recorded on my machine:
https://www.youtube.com/watch?v=93d7xJn5TD0

**Comment by coinfastman** [comment] 2019-10-02 11:39
Good afternoon. We also noticed problems with a memory leak after switching to version 77 of chrome.
We observe a problem on Windows and Linux systems. 
Firefox has no such problems. There is no leak if one tab with a remote connection or two is open. If you start immediately 5-6 tabs with a remote connection, then the consumed chrome memory grows in size and then leads to a browser failure.

**Comment by sotona-** [comment] 2019-10-02 11:41
Same problem.
Client: Chrome 77 on Ubuntu 18.04 + noVNC 1.1.0. 
Server: win10 + tightvnc + websockify 0.9.0

Memory is leaking on non active tab until OOM killer.

**Comment by coinfastman** [comment] 2019-10-02 11:56
I forgot to add that the leak occurs when the tab is inactive. If you go to the tab the memory is freed.
Leakage begins in 1 or 2 minutes. Moreover, in the chrome task manager, you can see that the memory of the process 'GPU process' begins to grow

**Comment by samhed** [comment] 2019-10-03 08:02
Could @sotona- and @gicuuu3 test if #1303 solves the memory leak issue for you?

**Comment by sotona-** [comment] 2019-10-03 10:03
@samhed, I confirm, no leaking anymore.

**Comment by coinfastman** [comment] 2019-10-03 10:25
Thanks. no leaking anymore.

**Comment by gicuuu3** [comment] 2019-10-03 12:54
@samhed It fixes the memory issue for inactive tabs.

There's one more edge case that lets memory leak: 
- Setting the noVNC canvas style to `display: none`

But, that's avoidable in our situation, so we can work around that.

Thank you for your work. You are awesome!

**Comment by samhed** [comment] 2019-10-05 21:07
Thanks for confirming!

**Comment by CourchesneA** [comment] 2019-10-12 17:00
> @samhed It fixes the memory issue for inactive tabs.
> 
> There's one more edge case that lets memory leak:
> 
> * Setting the noVNC canvas style to `display: none`
> 
> But, that's avoidable in our situation, so we can work around that.
> 
> Thank you for your work. You are awesome!

I am also having this issue. Google chome 77 with noVNC canvas style display:none, when the tab is inactive, after a few minutes all the RAM is getting used and my computer freezes

**Comment by CendioOssman** [comment] 2019-10-16 08:17
Hmm... I'm only almost seeing this. In my case I'm only seeing GPU memory go up. Normal RAM stays sane.

The GPU memory also doesn't go down for me when going back to the tab.

I'll see if I can compose a test case and submit a bug report.

**Comment by gicuuu3** [comment] 2019-10-16 08:20
@CendioOssman There is already a bug report and ongoing work on this.

https://bugs.chromium.org/p/chromium/issues/detail?id=1010922

Seems to be the situation, though I might be wrong.

**Comment by CendioOssman** [comment] 2019-10-16 08:39
Ah, thanks.

It seems they're taking this rather lightly though, given how badly it screws up your machine. I've written a comment there. Let's hope they reconsider and expedite a fix here.

**Comment by CendioOssman** [comment] 2019-11-01 07:57
Chrome 78 is now out, so this should be resolved. @gicuuu3, are you still seeing this?

**Comment by gicuuu3** [comment] 2019-11-08 14:16
@CendioOssman Hmm. I am still seeing it. If I run it without the `novnc only draw if document visible ` you guys offered in that patch, it eats up memory. Odd, I was expecting chrome 78 to have fixed it...

**Comment by samhed** [comment] 2019-12-08 17:49
It seems 78 fixed some issues but not all, someone at Chromium said (Dec 3) that he was working actively to fix a related issue:

https://bugs.chromium.org/p/chromium/issues/detail?id=1011812

**Comment by audiolion** [comment] 2020-01-29 23:28
@samhed bug tracker shows this is fixed as of 16 days ago

**Comment by samhed** [comment] 2020-01-30 08:03
Great!

**Closed by samhed** 2020-01-30 08:03 UTC
Labels: notourbug
