### ISSUE TITLE
Connection error with Firefox 55.0.3

### ISSUE THREAD

**Issue by zwick88** [novnc/noVNC#894] opened 2017-09-11 13:48 UTC
Hi everybody, 

on friday i've updatet my Firefox to 55.0.3. Since the new Version i cant connect to any server. in Internet Explorer or Chrom it works. 

Do anyone knows that issue?

**Comment by CendioOssman** [comment] 2017-09-11 14:51
That version works well here. What error are you getting? Is there anything in the browser error console?

**Comment by rmarder** [comment] 2017-09-13 05:09
Hello,

I am able to confirm this issue. I'm using NoVNC from today's master along with websockify 0.8

On Firefox 55.0.3 I observe "Error While Connecting" message in the NoVNC WebUI.

I have confirmed that downgrading to Firefox 54.0 solves the problem, and I have also confirmed no problem with latest Seamonkey 2.48 which uses the same engine as Firefox, as tested on Win10 x64.

This is the entire log from the Firefox Console on the non-working version:

window.controllers is deprecated. Do not use it for UA detection.  index.html
unreachable code after return statement  babel-worker.js:13014:4
unreachable code after return statement  babel-worker.js:13026:4
unreachable code after return statement  babel-worker.js:13014:4
unreachable code after return statement  babel-worker.js:13026:4
unreachable code after return statement  babel-worker.js:13014:4
unreachable code after return statement  babel-worker.js:13026:4
unreachable code after return statement babel-worker.js:43349:1
Failed when connecting: Error while connecting (SecurityError: The operation is insecure.)  rfb.js!transpiled:604:29
	_fail http://1.2.3.4:39341/core/rfb.js!transpiled:604:29
	_connect http://1.2.3.4:39341/core/rfb.js!transpiled:417:29
	_updateConnectionState http://1.2.3.4:39341/core/rfb.js!transpiled:572:29
	connect http://1.2.3.4:39341/core/rfb.js!transpiled:285:21
	execute/< http://1.2.3.4:39341/%3Canon1%3E!transpiled:196:17
	execute http://1.2.3.4:39341/%3Canon1%3E!transpiled:171:14
	declarativeExecute http://1.2.3.4:39341/vendor/browser-es-module-loader/dist/browser-es-module-loader.js:1149:5
	doEvaluate http://1.2.3.4:39341/vendor/browser-es-module-loader/dist/browser-es-module-loader.js:1078:13
	ensureEvaluate http://1.2.3.4:39341/vendor/browser-es-module-loader/dist/browser-es-module-loader.js:1011:13
	RegisterLoader$1.prototype[Loader.resolveInstantiate]/</< http://1.2.3.4:39341/vendor/browser-es-module-loader/dist/browser-es-module-loader.js:612:14

My NoVNC URL's look like this:

http://1.2.3.4:39341/index.html?host=1.2.3.4&port=39341&password=123456

I'm not using any kind of SSL at all, and as you can see, SameOrigin should not be an issue here. On my system I rename vnc_lite.html to index.html, no other changes made on my end from master. I confirm the same issue affects regular vnc.html too.

**Comment by rmarder** [comment] 2017-09-13 05:45
As an update, on Firefox 55.0.3 setting network.websocket.allowInsecureFromHTTPS to true in about:config restores the expected behavior. That makes no sense to me, since HTTPS is not involved at any stage of the request at all.

It is likely that this is a Firefox bug/regression. I've filed a bug with Mozilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1399354

**Comment by zwick88** [comment] 2017-09-13 05:47
Thank you very much, it works now

**Comment by rmarder** [comment] 2017-09-13 06:08
The OP closed this issue, however this issue should not be considered fixed at this time. Setting insecure nonstandard Firefox feature flags is a workaround, not a proper fix.

**Comment by CendioOssman** [comment] 2017-09-13 07:56
It doesn't seem to be a general bug in Firefox though as I'm not able to reproduce it.

Could you try with `master` of websockify as well in case that's where the problem lies?

**Comment by rmarder** [comment] 2017-09-13 08:33
Hi,

Tried with latest master for websockify, same problem there too.

I have been studying this more, and it takes a specific sequence of things that have to happen to trigger this.

First, I'm dropping websockify into the utils directory and running it with novnc like this:

./utils/launch.sh --listen 5901 --vnc someotherhost:5901

Second, I'm creating a file that does a meta refresh redirection, such as:

<html><head><meta http-equiv="refresh" content="1;URL='http://1.2.3.4:5901/vnc_lite.html?host=1.2.3.4&port=5901&password=123'"></head><body></body></html>

And hosting that redirection file on an external https site somewhere outside of novnc / websockify.

It seems, that Firefox, upon processing the meta refresh redirect, going from an https site to an http site, it doesn't properly register that the browser is no longer in an https context, so that causes trying to open an unencypted websocket from an http site to fail. Without that redirection step, accessing novnc over http is fine.

This definitely looks like a firefox bug to me.

**Comment by CendioOssman** [comment] 2017-09-13 08:55
Possibly. They could also argue that the user thinks they're on a https site since that's what they entered/clicked.

In any case it is not a noVNC issue, so please continue the discussion in Mozilla's bugzilla.

**Closed by CendioOssman** 2017-09-13 08:55 UTC
