### ISSUE TITLE
Regression: Partial screen updates in raw encoding result in garbled screen

### ISSUE THREAD

**Issue by tdobes** [novnc/noVNC#1635] opened 2022-03-19 18:33 UTC
After commit 6a19390baafedbc2729597fe244010a2aaadc068, raw encoding sessions result in a garbled and unusable screen.  It appears that there was a logic change in `core/display.js` which caused this issue.

Note that this only impacts VNC sessions which use raw encoding.  Other encodings still appear to work normally, so you must disable them (or use a server which only supports raw encoding) to observe this bug.

**To Reproduce**
Connect to a system and ensure that you're using raw encoding (type 0).  If the system sends partial screen updates, you'll see a garbled display similar to this one:
![garbled_macos_login_screen_novnc](https://user-images.githubusercontent.com/7492211/159132979-26f1e7b7-5cd8-4fbe-974d-eec22881380a.png)
(That's an example MacOS login screen in noVNC after moving the mouse around a bit)

I spent some time investigating a fix for this.  I've narrowed down the problem to this change...

New code in `core/display.js` in the `blitImage()` function which causes the bug:
https://github.com/novnc/noVNC/blob/7730814b8d43d24db0894b641317be4b9f683da4/core/display.js#L387-L390

Old code from `core/display.js` in the `_bgrxImageData()` function (which was called by `blitImage()`):
https://github.com/novnc/noVNC/blob/f5b5767c980da9fe5e2cb388eaa55c4368abd780/core/display.js#L450-L457

It needs a slight tweak to forward-port it (RGB vs BGR), but the below can be used as a direct replacement for the non-working code on the master branch:
```
            let img = this._drawCtx.createImageData(width, height);
            let data = img.data;
            for (let i = 0, j = offset; i < width * height * 4; i += 4, j += 4) {
                data[i]     = arr[j];
                data[i + 1] = arr[j + 1];
                data[i + 2] = arr[j + 2];
                data[i + 3] = 255;  // Alpha
            }
```

Tested with noVNC master (7730814b8d43d24db0894b641317be4b9f683da4).  VNC server was MacOS 11.5.2 and an Ubuntu 18.04 system running TigerVNC.  Client was Chrome 99.0.4844.74 and Firefox 91.7.0esr.  Note that the problem also occurs in the 1.3.0 release.

I'm not sure I fully understand how this section of new code introduced in 6a19390b is intended to work, so I'm hesitant to make a PR to fix this.  The tweaked old code (listed above) does fix the problem I'm observing, but I don't have the resources to run exhaustive tests to ensure that it doesn't cause issues for other encodings or platforms.

**Comment by samhed** [comment] 2022-03-21 18:17
Thanks for finding this!

Could this be a server bug in TigerVNC? Perhaps the code for the raw encoding doesn't support RGBx, and only BGRx? Thoughts @CendioOssman?

@tdobes would you have the possibility of testing with a different client when connecting to this VNC server? Also, if you can, could you test a different VNC server?

**Comment by samhed** [comment] 2022-03-22 08:13
Greatly appreciated. Thank you for verifying that @tdobes

Me or some other maintainer will have a look at this once we find some time.

**Comment by CendioOssman** [comment] 2022-03-24 12:15
I think I see the issue. Could you try with this change:

```diff
diff --git a/core/decoders/raw.js b/core/decoders/raw.js
index e8ea178..d08f7ba 100644
--- a/core/decoders/raw.js
+++ b/core/decoders/raw.js
@@ -51,7 +51,7 @@ export default class RawDecoder {
 
         // Max sure the image is fully opaque
         for (let i = 0; i < pixels; i++) {
-            data[i * 4 + 3] = 255;
+            data[index + i * 4 + 3] = 255;
         }
 
         display.blitImage(x, curY, width, currHeight, data, index);
```

**Comment by tdobes** [comment] 2022-03-24 15:06
I can confirm that the proposed change from @CendioOssman fixes the problem.  (using an otherwise clean source tree)  I tested this against a few different pieces of server software using raw encoding and observed no problems or visual glitches.  Thank you!

**Comment by CendioOssman** [comment] 2022-03-28 06:47
Thanks for testing! The issue is now fixed in 98664c78871bf9e1c6c8914e68196fc4350a21cd.

**Closed by CendioOssman** 2022-03-28 06:47 UTC
Labels: bug

**Comment by freebrowser1** [comment] 2022-05-30 14:31
This indeed does work when macOS (Monterey 12.3) as a server for `novnc`.

**Comment by ogbozoyan** [comment] 2024-06-16 21:22
Could you please describe steps how to use noVNC with macOS builtin tools 
I've been trying to setup connection for straight 6 hours and nothing booted up
I'm trying use noVNC as client on other macbook in local network to connect my other mac - VNC server. After i'll try to expose to wan for remote usage, but before all please help with setting up, i'm completely stack :(
